# Generated by Django 4.2.30 on 2026-06-07 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chaisImg/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('PL', 'PLAIN'), ('GR', 'GINGER'), ('EL', 'ELAYCHI'), ('BL', 'BLACK')], max_length=2)),
            ],
        ),
    ]
