# Generated by Django 4.2.30 on 2026-06-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.IntegerField(default=90),
        ),
    ]
